import { cn } from "@/lib/utils"
import "@/app/globals.css"
import type { Metadata } from "next"
import { jetbrains_mono, inter } from "@/app/fonts"

import { ThemeProvider } from "@/providers/theme-provider"

export const metadata: Metadata = {
  title: "Kian Bazarjani",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          jetbrains_mono.variable,
          inter.variable,
          "min-h-screen max-w-xl flex flex-col gap-10 m-auto py-12 px-8 dark:bg-black"
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
