import { cn } from "@/lib/utils"
import "@/app/globals.css"
import type { Metadata } from "next"
import { jetbrains_mono, inter } from "@/app/fonts"

export const metadata: Metadata = {
  title: "Kian Bazarjani",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          jetbrains_mono.variable,
          inter.variable,
          "min-h-screen max-w-xl flex flex-col m-auto p-10"
        )}
      >
        {children}
      </body>
    </html>
  )
}
