import { cn } from '@/lib/utils'
import '@/app/globals.css'
import type { Metadata } from 'next'
import { jetbrains_mono, inter } from '@/app/fonts'

import { ThemeProvider } from '@/providers/theme-provider'

export const metadata: Metadata = {
  title: 'Kian Bazarjani',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <head />
      <body
        className={cn(
          jetbrains_mono.variable,
          inter.variable,
          'dark:bg-zinc-900',
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  )
}
