import '@/app/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Kian Bazarjani',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="m-auto flex min-h-screen max-w-xl flex-col gap-10 px-8 py-12 ">
      {children}
    </div>
  )
}
